   --E-COMMERCE DATA ANALYSIS PROJECT
   --AUTHOR: PIYUSH SHARMA
   --DESCRIPTION: 
   --SQL BASED ANALYSIS OF E-COMMERCE DATASET OF PRODUCTS, REVENUE, RATINGS, AND OTHER KEY METRICS.
   --including basic, intermediate, and advanced analyses to derive insights .

   
-- =========================
-- CREATE TABLE
-- =========================
CREATE TABLE ecommerce (
    product_id INT,
    product_name VARCHAR(50),
    category VARCHAR(50),
    price DECIMAL(10,2),
    rating FLOAT,
    reviews INT,
    stock INT,
    discount DECIMAL(5,2),
    revenue DECIMAL(10,2),
    date_added DATE,
    city VARCHAR(50),
    stock_status VARCHAR(10)
);

--=========================
--DATA LOADING
--=========================

USE ecomm_proj;
--NOTE: UPDATE THE FILE PATH IN THE BELOW QUERY TO MATCH THE LOCATION OF YOUR CSV FILE ON YOUR SYSTEM

LOAD DATA LOCAL INFILE 'F:/ecomm sales analysis/ecommerce_product_dataset2.csv'
INTO TABLE ecommerce
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;



-- =========================
-- BASIC ANALYSIS
-- =========================

-- calculate total revenue generated by all products
SELECT SUM(revenue) AS total_revenue
FROM ecommerce;

-- Top 5 Products by Revenue
SELECT product_name, SUM(revenue) AS total_revenue
FROM ecommerce
GROUP BY product_name
ORDER BY total_revenue DESC
LIMIT 5;

-- =========================
-- INTERMEDIATE ANALYSIS
-- =========================

-- Best Rated Products
SELECT product_name, rating
FROM ecommerce
ORDER BY rating DESC
LIMIT 5;

-- Revenue by City
SELECT city, SUM(revenue) AS total_revenue
FROM ecommerce
GROUP BY city
ORDER BY total_revenue DESC;

-- Low Stock Products
SELECT product_name, stock
FROM ecommerce
WHERE stock < 50;

-- Category-wise Average Rating
SELECT category, AVG(rating) AS avg_rating
FROM ecommerce
GROUP BY category
ORDER BY avg_revenue DESC;

-- Category-wise Average Rating
SELECT category, SUM(revenue) AS total_revenue
FROM ecommerce
GROUP BY category;

-- =========================
-- ADVANCED ANALYSIS
-- =========================

-- Product Ranking
SELECT product_name,
SUM(revenue) AS total_revenue,
RANK() OVER (ORDER BY SUM(revenue) DESC) AS rank_position
FROM ecommerce
GROUP BY product_name;

-- Revenue Contribution %
SELECT product_name,
SUM(revenue) AS revenue,
ROUND(SUM(revenue) * 100 / (SELECT SUM(revenue) FROM ecommerce), 2) AS percentage
FROM ecommerce
GROUP BY product_name
ORDER BY percentage DESC;

-- Category-wise Average Rating
SELECT category,
AVG(rating) AS avg_rating
FROM ecommerce
GROUP BY category
ORDER BY avg_rating DESC;
